### ISSUE TITLE
Best practice to host a remote config file in a http server

### ISSUE THREAD

**Issue by jeberdson** [play-rconf/play-rconf-http#4]
Hi @thibaultmeyer ,

I am using play-rconf-http for implementing remote configuration in my play application.

I tried to set the **"remote-configuration.http.url"** as raw github content as shown below,

`remote-configuration.http.url = "https://raw.github.xxx.com/sample-repo/config-details/master/conf/application-dev.conf?token=ABAD5JUZ7O84U7CIKEU4MGY5UWJU6"`

It worked well, but after a week the token got expired. So I am getting "404: Not found" when I try to fetch the file.

Is there any way to prevent the token from expiring or any better solution to solve this problem?

```
play.application.loader ="io.playrconf.ApplicationLoaderScala"
play.filters.enabled += "play.filters.cors.CORSFilter"
play.modules.enabled += "play.modules.swagger.SwaggerModule"
remote-configuration.provider = "io.playrconf.provider.HttpProvider"
remote-configuration.http.url = "https://raw.github.ford.com/OCPP-Server/ocpp-config-server/master/ocpp-server/ocpp-server-dev.conf?token=AAAD5JW3OTRF3RJKF66OBC25UWRFO"
```

Please help to solve this issue.

**Comment by jeberdson** [comment]
@thibaultmeyer did you find any idea or solution?

**Comment by thibaultmeyer** [comment]
Hi @jeberdson

You may have another way to access this file? without token in GET, but via the use of OAuth with "Resource Owner Password" flow.

If your Gist instance allows it, we can probably add OAuth as an authentication mechanism (currently, project only works with Basic auth)

**Comment by jeberdson** [comment]
@thibaultmeyer ,

Yes our gist instance allows OAuth. Can you add OAuth authentication feature?

**Comment by thibaultmeyer** [comment]
@jeberdson,

I'll see what we can do to add OAUth2

**Comment by jeberdson** [comment]
@thibaultmeyer ,
Ok thank you. please post here if you have any updates regarding it.

**Comment by jeberdson** [comment]
Hi @thibaultmeyer , do you have any updates regarding this enhancement?

**Comment by thibaultmeyer** [comment]
Hello @jeberdson, I only made a quick design of this feature. Basically, authentication management does not exist in the Typesafe Config library. It will therefore be necessary to handle transport and authentication.

**Could you validate on your side (ie: with postman by example) that your file is accessible after you have retrieved your OAuth Token ?**

because I try Github Gist and secret file are still accessible via direct access without authentication.

I don't have OAuth server to test against.

If you want, you can create a merge request too.

**STEPS**
1. POST request to retrieve OAuth token via username/password
2. Use token for the GET query

(Configuration need an extra entry: URL of the token endpoint)

**Comment by jeberdson** [comment]
@thibaultmeyer , Sorry for my late reply. I was on holidays and still I am. Will be back to work in couple of days.

I will validate using postman and update my comments here. Thanks for your continuous support.

**Comment by jeberdson** [comment]
Hi @thibaultmeyer ,
We decided to use a http server for hosting our config files with basic authentication itself and read it using play-rconf-http.
So I am closing this issue.
Thanks for your support.
